title: AdZ
description: AdZ Home page
theme: just-the-docs

url: https://johansolhed.github.io/AdZ

logo: "/assets/images/Icon-29x29@3x.png"

search_enabled: true

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
